# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(421, 461)
        self.graphicsView = QtWidgets.QGraphicsView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(10, 50, 401, 401))
        self.graphicsView.setObjectName("graphicsView")
        self.cordsInput = QtWidgets.QTextEdit(Form)
        self.cordsInput.setGeometry(QtCore.QRect(10, 10, 331, 31))
        self.cordsInput.setObjectName("cordsInput")
        self.enterButton = QtWidgets.QPushButton(Form)
        self.enterButton.setGeometry(QtCore.QRect(350, 10, 61, 31))
        self.enterButton.setObjectName("enterButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "static-map"))
        self.enterButton.setText(_translate("Form", "ОК"))
